# Try-catch
trying my first exception 
